"""add scientific_concepts_and_directed_relationships_tables

Revision ID: 5c1c5a5a7f7e
Revises: rev_0003
Create Date: 2024-07-26 10:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Importar el tipo UUID personalizado y el Enum de dominio para la migración
# Alembic necesita acceso a estas definiciones para crear los tipos correctamente en la BD.
from aletheia_common.db.custom_types import UUID as CommonUUID
from Aletheia_v3.core.domain_models import ConceptType

# revision identifiers, used by Alembic.
revision: str = '5c1c5a5a7f7e'
down_revision: Union[str, None] = 'rev_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scientific_concepts',
    sa.Column('id', CommonUUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('concept_type', sa.Enum(ConceptType, name='concept_type_enum_v2', create_constraint=True), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scientific_concepts_concept_type'), 'scientific_concepts', ['concept_type'], unique=False)
    op.create_index(op.f('ix_scientific_concepts_name'), 'scientific_concepts', ['name'], unique=False)

    op.create_table('directed_relationships',
    sa.Column('id', CommonUUID(as_uuid=True), nullable=False),
    sa.Column('source_concept_id', CommonUUID(as_uuid=True), nullable=False),
    sa.Column('target_concept_id', CommonUUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_concept_id'], ['scientific_concepts.id'], name='fk_relationship_source_concept'),
    sa.ForeignKeyConstraint(['target_concept_id'], ['scientific_concepts.id'], name='fk_relationship_target_concept'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directed_relationships_source_concept_id'), 'directed_relationships', ['source_concept_id'], unique=False)
    op.create_index(op.f('ix_directed_relationships_target_concept_id'), 'directed_relationships', ['target_concept_id'], unique=False)
    op.create_index(op.f('ix_directed_relationships_type'), 'directed_relationships', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_directed_relationships_type'), table_name='directed_relationships')
    op.drop_index(op.f('ix_directed_relationships_target_concept_id'), table_name='directed_relationships')
    op.drop_index(op.f('ix_directed_relationships_source_concept_id'), table_name='directed_relationships')
    op.drop_table('directed_relationships')

    op.drop_index(op.f('ix_scientific_concepts_name'), table_name='scientific_concepts')
    op.drop_index(op.f('ix_scientific_concepts_concept_type'), table_name='scientific_concepts')
    op.drop_table('scientific_concepts')

    # Drop the ENUM type associated with ConceptType
    sa.Enum(ConceptType, name='concept_type_enum_v2').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
