"""create_initial_tables

Revision ID: init_0001
Revises:
Create Date: YYYY-MM-DD HH:MM:SS.MS # Alembic llenará esto

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import (
    postgresql,  # Para tipos específicos de PostgreSQL como UUID
)

# revision identifiers, used by Alembic.
revision = "init_0001"
down_revision = None  # Esta es la primera migración
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Crear tipos ENUM primero si no se manejan automáticamente por SAEnum con `name`
    # Para PostgreSQL, SAEnum(..., name="...") debería manejarlos, pero por si acaso:
    # contribution_type_enum = postgresql.ENUM('DISCOVERED_BY_JOB', 'VERIFIED_BY_USER', 'ANALYZED_BY_USER', 'TAGGED_BY_USER', name='contribution_type_enum', create_type=False)
    # contribution_type_enum.create(op.get_bind(), checkfirst=True)
    # conjecture_status_enum = postgresql.ENUM('PROPOSED', 'UNDER_REVIEW', 'VALIDATED', 'REFUTED', 'NEEDS_MORE_EVIDENCE', name='conjecture_status_enum', create_type=False)
    # conjecture_status_enum.create(op.get_bind(), checkfirst=True)
    # Nota: Si SAEnum(name=...) funciona, no se necesitan estas creaciones explícitas de ENUM aquí.
    # SQLAlchemy 2.0 con SAEnum(name=...) para PG generalmente lo maneja.

    op.create_table(
        "researchers",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("orcid", sa.String(length=50), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_researchers_email"), "researchers", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_researchers_orcid"), "researchers", ["orcid"], unique=True
    )
    op.create_index(
        op.f("ix_researchers_username"),
        "researchers",
        ["username"],
        unique=True,
    )

    op.create_table(
        "discovery_jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("n_calls", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "submitter_id", postgresql.UUID(as_uuid=True), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["submitter_id"],
            ["researchers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discovery_jobs_id"), "discovery_jobs", ["id"], unique=False
    )  # unique=False es el default para index
    op.create_index(
        op.f("ix_discovery_jobs_status"),
        "discovery_jobs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discovery_jobs_submitter_id"),
        "discovery_jobs",
        ["submitter_id"],
        unique=False,
    )

    op.create_table(
        "discovery_hits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("a", sa.Integer(), nullable=False),
        sa.Column("b", sa.Integer(), nullable=False),
        sa.Column("c", sa.Integer(), nullable=False),
        sa.Column("quality", sa.Float(), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["discovery_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discovery_hits_id"), "discovery_hits", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_discovery_hits_job_id"),
        "discovery_hits",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discovery_hits_quality"),
        "discovery_hits",
        ["quality"],
        unique=False,
    )

    op.create_table(
        "derived_conjectures",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PROPOSED",
                "UNDER_REVIEW",
                "VALIDATED",
                "REFUTED",
                "NEEDS_MORE_EVIDENCE",
                name="conjecture_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "proposer_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["proposer_id"],
            ["researchers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_derived_conjectures_id"),
        "derived_conjectures",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_derived_conjectures_proposer_id"),
        "derived_conjectures",
        ["proposer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_derived_conjectures_status"),
        "derived_conjectures",
        ["status"],
        unique=False,
    )

    op.create_table(
        "discovery_attributions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("hit_id", sa.Integer(), nullable=False),
        sa.Column(
            "researcher_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column(
            "contribution_type",
            sa.Enum(
                "DISCOVERED_BY_JOB",
                "VERIFIED_BY_USER",
                "ANALYZED_BY_USER",
                "TAGGED_BY_USER",
                name="contribution_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column(
            "attributed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["hit_id"],
            ["discovery_hits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["researcher_id"],
            ["researchers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discovery_attributions_hit_id"),
        "discovery_attributions",
        ["hit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discovery_attributions_id"),
        "discovery_attributions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discovery_attributions_researcher_id"),
        "discovery_attributions",
        ["researcher_id"],
        unique=False,
    )

    op.create_table(
        "conjecture_hits_association",
        sa.Column("conjecture_id", sa.Integer(), nullable=False),
        sa.Column("hit_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conjecture_id"],
            ["derived_conjectures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hit_id"],
            ["discovery_hits.id"],
        ),
        sa.PrimaryKeyConstraint("conjecture_id", "hit_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conjecture_hits_association")
    op.drop_index(
        op.f("ix_discovery_attributions_researcher_id"),
        table_name="discovery_attributions",
    )
    op.drop_index(
        op.f("ix_discovery_attributions_id"),
        table_name="discovery_attributions",
    )
    op.drop_index(
        op.f("ix_discovery_attributions_hit_id"),
        table_name="discovery_attributions",
    )
    op.drop_table("discovery_attributions")

    op.drop_index(
        op.f("ix_derived_conjectures_status"), table_name="derived_conjectures"
    )
    op.drop_index(
        op.f("ix_derived_conjectures_proposer_id"),
        table_name="derived_conjectures",
    )
    op.drop_index(
        op.f("ix_derived_conjectures_id"), table_name="derived_conjectures"
    )
    op.drop_table("derived_conjectures")

    op.drop_index(
        op.f("ix_discovery_hits_quality"), table_name="discovery_hits"
    )
    op.drop_index(
        op.f("ix_discovery_hits_job_id"), table_name="discovery_hits"
    )
    op.drop_index(op.f("ix_discovery_hits_id"), table_name="discovery_hits")
    op.drop_table("discovery_hits")

    op.drop_index(
        op.f("ix_discovery_jobs_submitter_id"), table_name="discovery_jobs"
    )
    op.drop_index(
        op.f("ix_discovery_jobs_status"), table_name="discovery_jobs"
    )
    op.drop_index(op.f("ix_discovery_jobs_id"), table_name="discovery_jobs")
    op.drop_table("discovery_jobs")

    op.drop_index(op.f("ix_researchers_username"), table_name="researchers")
    op.drop_index(op.f("ix_researchers_orcid"), table_name="researchers")
    op.drop_index(op.f("ix_researchers_email"), table_name="researchers")
    op.drop_table("researchers")

    # Si los ENUM se crearon explícitamente, también se deben eliminar aquí:
    # op.execute("DROP TYPE contribution_type_enum;")
    # op.execute("DROP TYPE conjecture_status_enum;")
    # ### end Alembic commands ###
