# Copyright 2025 Alant
#
# Licensed under the Aletheia Unificada Ethical Public License (AUEPL);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add_is_admin_to_researchers

Revision ID: rev_0002
Revises: init_0001
Create Date: 2024-07-30 12:00:00.000000 # Placeholder date

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "rev_0002"
down_revision = (
    "init_0001"  # Debe coincidir con el ID de la revisión anterior real
)
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "researchers",
        sa.Column(
            "is_admin",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # Se establece server_default para que las filas existentes obtengan un valor, y nullable=False para nuevas filas.
    # Para asegurar que las filas existentes realmente obtengan 'false' si el server_default no se aplica retroactivamente
    # en todas las BD de la misma manera, o si la columna se añade primero y luego se altera:
    # op.execute("UPDATE researchers SET is_admin = false WHERE is_admin IS NULL") # Opcional, si es necesario.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("researchers", "is_admin")
    # ### end Alembic commands ###
