"""add_disabled_to_researchers

Revision ID: rev_0003
Revises: rev_0002
Create Date: 2024-07-25 14:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "rev_0003"
down_revision = "rev_0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "researchers",
        sa.Column(
            "disabled", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
    )
    # Ensure existing rows get a default value if server_default doesn't apply retroactively
    # For PostgreSQL, server_default works for new rows; existing rows will get the Python default (False)
    # if the column is added as nullable first then altered to not nullable.
    # Since we add it as nullable=False with a server_default, it should be fine.
    # If explicit update for existing rows needed:
    # op.execute("UPDATE researchers SET disabled = FALSE WHERE disabled IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("researchers", "disabled")
    # ### end Alembic commands ###
