# Copyright 2025 Alant
#
# Licensed under the Aletheia Unificada Ethical Public License (AUEPL);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add_disabled_to_researchers

Revision ID: rev_0003
Revises: rev_0002
Create Date: 2024-07-25 14:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "rev_0003"
down_revision = "rev_0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "researchers",
        sa.Column(
            "disabled", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
    )
    # Ensure existing rows get a default value if server_default doesn't apply retroactively
    # For PostgreSQL, server_default works for new rows; existing rows will get the Python default (False)
    # if the column is added as nullable first then altered to not nullable.
    # Since we add it as nullable=False with a server_default, it should be fine.
    # If explicit update for existing rows needed:
    # op.execute("UPDATE researchers SET disabled = FALSE WHERE disabled IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("researchers", "disabled")
    # ### end Alembic commands ###
