-- Aletheia_v3/infrastructure/db_optimizations.sql
-- This script contains examples of advanced database optimizations for PostgreSQL
-- that can be applied to handle massive storage of discovery_jobs and discovery_hits.
-- These commands are typically applied by a Database Administrator (DBA)
-- after the initial schema creation by SQLAlchemy's `Base.metadata.create_all()`.

-- Important Note: Applying partitioning changes the table structure.
-- SQLAlchemy's default ORM behavior might need adjustments or specific querying
-- strategies if it's not aware of the partitioning. For basic CRUD, it usually works,
-- but performance benefits of partitioning are best realized with partition-aware queries.

-- Section 1: Table Partitioning for `discovery_hits`
-- Partitioning `discovery_hits` by the `quality` field can significantly improve query
-- performance when filtering or analyzing hits within specific quality ranges.
-- It can also help with data management (e.g., archiving or deleting old low-quality partitions).

-- First, ensure the main `discovery_hits` table is created by SQLAlchemy.
-- Then, it needs to be defined as a PARTITIONED table.
-- If `discovery_hits` already exists and has data, it would need to be migrated.
-- For a new setup, you might create `discovery_hits` as partitioned from the start,
-- which SQLAlchemy's `create_all` doesn't directly support declaratively for all DBs.

-- Assuming `discovery_hits` table exists (created by `Base.metadata.create_all()`).
-- The following is conceptual if table is already populated.
-- For a fresh setup, one might define `discovery_hits` as PARTITION BY RANGE (quality)
-- and then create partitions.

-- Example: If we were to recreate discovery_hits as a partitioned table (manual DDL step):
/*
ALTER TABLE discovery_hits RENAME TO discovery_hits_old;

CREATE TABLE discovery_hits (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    job_id VARCHAR NOT_NULL,
    a INTEGER NOT NULL,
    b INTEGER NOT NULL,
    c INTEGER NOT NULL,
    quality FLOAT NOT NULL,
    discovered_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, quality), -- Partition key must be part of the primary key
    FOREIGN KEY(job_id) REFERENCES discovery_jobs (id) ON DELETE CASCADE
) PARTITION BY RANGE (quality);

-- Create partitions for different quality ranges:
-- Note: MAXVALUE can be used for the upper bound of the last partition.
-- Ensure ranges are contiguous and cover all expected values.

CREATE TABLE discovery_hits_q_low PARTITION OF discovery_hits
    FOR VALUES FROM (MINVALUE) TO (1.2); -- Hits with quality < 1.2

CREATE TABLE discovery_hits_q_medium PARTITION OF discovery_hits
    FOR VALUES FROM (1.2) TO (1.4); -- Hits with 1.2 <= quality < 1.4

CREATE TABLE discovery_hits_q_high PARTITION OF discovery_hits
    FOR VALUES FROM (1.4) TO (1.6); -- Hits with 1.4 <= quality < 1.6

CREATE TABLE discovery_hits_q_very_high PARTITION OF discovery_hits
    FOR VALUES FROM (1.6) TO (MAXVALUE); -- Hits with quality >= 1.6

-- Don't forget to create indexes on partitions as well, or on the parent partitioned table (PostgreSQL 11+)
-- CREATE INDEX idx_hits_job_id_q_low ON discovery_hits_q_low (job_id); (Example for older PG)
-- CREATE INDEX idx_hits_quality_q_low ON discovery_hits_q_low (quality DESC);
-- For PG11+, indexes on parent table propagate to partitions.
-- The existing indexes on `discovery_hits` (job_id, quality) would propagate if created on the partitioned table.
*/

-- Since modifying `init_db` to handle this complex DDL is out of scope for automation here,
-- this section serves as a guideline for manual DBA actions.
-- The `Base.metadata.create_all()` will create a non-partitioned table.
-- If partitioning is critical, `init_db` would need to be significantly more complex or replaced
-- by a migration tool like Alembic that can handle such DDL.

-- Section 2: Specialized Indexing
-- These indexes can be added to the non-partitioned table created by SQLAlchemy,
-- or to the main partitioned table (and they will propagate to partitions in PG11+).

-- Index for searching hits by job_id and then by quality (useful for fetching results of a specific job)
-- SQLAlchemy model already has index=True for job_id and quality, which should create individual indexes.
-- A composite index might be beneficial too.
CREATE INDEX IF NOT EXISTS idx_discovery_hits_job_id_quality ON discovery_hits (job_id, quality DESC);

-- Index for common mathematical queries, if analyzing properties of a, b, c directly.
-- These are examples; actual useful indexes depend on query patterns.
-- Indexing on expressions can be powerful but use judiciously.

-- Example: Index on `c` if frequently searching/sorting by the sum.
-- (The `models.py` already has `c` as a column, it could be indexed there if not already)
-- CREATE INDEX IF NOT EXISTS idx_discovery_hits_c ON discovery_hits (c);

-- Example: Index for searching for "symmetric" hits if a and b were interchangeable in queries.
-- (Not typically needed due to a < b constraint in get_quality)
-- CREATE INDEX IF NOT EXISTS idx_discovery_hits_a_b ON discovery_hits (LEAST(a,b), GREATEST(a,b));

-- Index on `discovered_at` if time-based analysis of hits is common.
CREATE INDEX IF NOT EXISTS idx_discovery_hits_discovered_at ON discovery_hits (discovered_at DESC);


-- Section 3: Optimizing `discovery_jobs` table
-- This table is smaller, but good indexing is still important.

-- The model `JobDB` already has `index=True` for `id` (primary key) and `status`.
-- A composite index on (status, created_at) might be useful for querying jobs by status over time.
CREATE INDEX IF NOT EXISTS idx_discovery_jobs_status_created_at ON discovery_jobs (status, created_at DESC);


-- Section 4: General PostgreSQL Performance Tuning (DBA Level - Conceptual)
-- These are not SQL commands but general advice.
-- 1. Regular VACUUM and ANALYZE: Ensure autovacuum is properly configured, or run these manually
--    periodically, especially after large data loads/deletions.
--    `VACUUM ANALYZE discovery_hits;`
--    `VACUUM ANALYZE discovery_jobs;`
-- 2. Connection Pooling: Use a connection pooler (like PgBouncer) in front of PostgreSQL,
--    especially for applications with many short-lived connections (FastAPI + Celery can generate many).
--    SQLAlchemy has its own pooling but an external pooler is better for many app instances.
-- 3. Configuration Tuning (`postgresql.conf`):
--    - `shared_buffers`: Increase based on available RAM (e.g., 25% of RAM).
--    - `work_mem`: Increase for complex sorts/joins, per connection.
--    - `effective_cache_size`: Set to a large portion of RAM (e.g., 50-75%).
--    - `maintenance_work_mem`: For VACUUM, CREATE INDEX, etc.
--    - Checkpoint tuning (`checkpoint_segments` or `max_wal_size`, `checkpoint_completion_target`).
-- 4. Hardware: Sufficient RAM, fast SSDs for storage.

-- Section 5: Data Compression and Storage Types (Conceptual)
-- - PostgreSQL 14+ offers ZSTD compression for TOASTed data (large values).
-- - Use appropriate data types: `INTEGER` vs `BIGINT` for a, b, c depending on expected magnitude.
--   `models.py` currently uses `Integer`. If numbers can exceed 2 billion, `BIGINT` (SQLAlchemy's `BigInteger`) is needed.
--   The ABC conjecture involves potentially very large numbers.
-- - Archiving: For extremely large datasets, consider strategies to archive older or less relevant
--   data to cheaper storage, or aggregate it.

-- This script is intended as a reference for database optimization strategies.
-- Apply changes carefully and test their impact in a staging environment.
```
