# Aletheia_v3/tests/infrastructure/test_sqlalchemy_repositories.py
import pytest
import pytest_asyncio
from unittest.mock import MagicMock, patch
import uuid
from datetime import datetime, timezone
from typing import List, Optional

from sqlalchemy.orm import Session

# Modules to test
from Aletheia_v3.infrastructure.sqlalchemy_repositories import (
    SQLAlchemyConceptRepository,
    SQLAlchemyRelationshipRepository,
    _map_concept_db_to_domain, # Helper for creating expected domain objects
    _map_relationship_db_to_domain
)
# DB Models (for creating mock return values from DB)
from Aletheia_v3.infrastructure.models import ScientificConceptDB, DirectedRelationshipDB
# Domain Models (for creating input to repo methods and for expected output)
from Aletheia_v3.core.domain_models import ScientificConcept, DirectedRelationship, ConceptType

@pytest.fixture
def mock_db_session() -> MagicMock:
    """Fixture to create a mock SQLAlchemy Session."""
    return MagicMock(spec=Session)

# --- Tests for SQLAlchemyConceptRepository ---
class TestSQLAlchemyConceptRepository:

    @pytest_asyncio.fixture
    async def concept_repo(self, mock_db_session: MagicMock) -> SQLAlchemyConceptRepository:
        # Patch 'Depends(get_db_session)' implicitly by passing the mock session directly
        # This is simpler for unit testing the repository class in isolation.
        # In FastAPI, Depends resolves it. Here, we control instantiation.
        return SQLAlchemyConceptRepository(db=mock_db_session)

    @pytest.mark.asyncio
    async def test_add_concept(self, concept_repo: SQLAlchemyConceptRepository, mock_db_session: MagicMock):
        concept_id = uuid.uuid4()
        domain_concept = ScientificConcept(
            id=str(concept_id), name="Test Concept", description="A test concept",
            concept_type=ConceptType.UCM, properties={"key": "value"},
            created_at=datetime.now(timezone.utc), updated_at=datetime.now(timezone.utc)
        )

        await concept_repo.add(domain_concept)

        mock_db_session.add.assert_called_once()
        added_db_obj = mock_db_session.add.call_args[0][0]
        assert isinstance(added_db_obj, ScientificConceptDB)
        assert added_db_obj.id == concept_id
        assert added_db_obj.name == "Test Concept"
        mock_db_session.commit.assert_called_once()
        # refresh might not be called if add doesn't use it, but it's good practice if IDs are auto-generated by DB
        # For UUIDs generated client-side, refresh after add is less critical.

    @pytest.mark.asyncio
    async def test_get_by_id_found(self, concept_repo: SQLAlchemyConceptRepository, mock_db_session: MagicMock):
        concept_id_str = str(uuid.uuid4())
        concept_uuid = uuid.UUID(concept_id_str)

        mock_db_concept = ScientificConceptDB(
            id=concept_uuid, name="Found Concept", concept_type=ConceptType.CLUSTER,
            created_at=datetime.now(timezone.utc), updated_at=datetime.now(timezone.utc)
        )
        mock_db_session.query(ScientificConceptDB).filter(ScientificConceptDB.id == concept_uuid).first.return_value = mock_db_concept

        result = await concept_repo.get_by_id(concept_id_str)

        assert result is not None
        assert result.id == concept_id_str
        assert result.name == "Found Concept"
        assert result.concept_type == ConceptType.CLUSTER

    @pytest.mark.asyncio
    async def test_get_by_id_not_found(self, concept_repo: SQLAlchemyConceptRepository, mock_db_session: MagicMock):
        concept_id_str = str(uuid.uuid4())
        concept_uuid = uuid.UUID(concept_id_str)
        mock_db_session.query(ScientificConceptDB).filter(ScientificConceptDB.id == concept_uuid).first.return_value = None

        result = await concept_repo.get_by_id(concept_id_str)
        assert result is None

    @pytest.mark.asyncio
    async def test_list_all_with_pagination(self, concept_repo: SQLAlchemyConceptRepository, mock_db_session: MagicMock):
        mock_db_concepts = [
            ScientificConceptDB(id=uuid.uuid4(), name="Concept 1", concept_type=ConceptType.UCM, created_at=datetime.now(timezone.utc), updated_at=datetime.now(timezone.utc)),
            ScientificConceptDB(id=uuid.uuid4(), name="Concept 2", concept_type=ConceptType.PROPOSITION, created_at=datetime.now(timezone.utc), updated_at=datetime.now(timezone.utc))
        ]
        mock_query = mock_db_session.query(ScientificConceptDB)
        mock_query.offset().limit().all.return_value = mock_db_concepts

        result = await concept_repo.list_all(skip=5, limit=10)

        mock_query.offset.assert_called_with(5)
        mock_query.offset().limit.assert_called_with(10)
        mock_query.offset().limit().all.assert_called_once()

        assert len(result) == 2
        assert result[0].name == "Concept 1"

    @pytest.mark.asyncio
    async def test_count_all_concepts(self, concept_repo: SQLAlchemyConceptRepository, mock_db_session: MagicMock):
        mock_db_session.query().scalar.return_value = 5 # Mock the count scalar result

        count = await concept_repo.count_all()

        assert count == 5
        # Check that func.count was called on ScientificConceptDB.id
        # This is a bit more involved to assert correctly with MagicMock for chained calls like query(func.count(...))
        # For now, trusting the scalar return value is sufficient for this level of test.


# --- Tests for SQLAlchemyRelationshipRepository ---
class TestSQLAlchemyRelationshipRepository:

    @pytest_asyncio.fixture
    async def rel_repo(self, mock_db_session: MagicMock) -> SQLAlchemyRelationshipRepository:
        return SQLAlchemyRelationshipRepository(db=mock_db_session)

    @pytest.mark.asyncio
    async def test_add_relationship(self, rel_repo: SQLAlchemyRelationshipRepository, mock_db_session: MagicMock):
        rel_id = uuid.uuid4()
        source_id = uuid.uuid4()
        target_id = uuid.uuid4()
        domain_rel = DirectedRelationship(
            id=str(rel_id), source_concept_id=str(source_id), target_concept_id=str(target_id),
            type="RELATES_TO", description="Test relationship",
            created_at=datetime.now(timezone.utc), updated_at=datetime.now(timezone.utc)
        )

        await rel_repo.add(domain_rel)

        mock_db_session.add.assert_called_once()
        added_db_obj = mock_db_session.add.call_args[0][0]
        assert isinstance(added_db_obj, DirectedRelationshipDB)
        assert added_db_obj.id == rel_id
        assert added_db_obj.type == "RELATES_TO"
        mock_db_session.commit.assert_called_once()

    @pytest.mark.asyncio
    async def test_get_by_id_found_rel(self, rel_repo: SQLAlchemyRelationshipRepository, mock_db_session: MagicMock):
        rel_id_str = str(uuid.uuid4())
        rel_uuid = uuid.UUID(rel_id_str)

        mock_db_rel = DirectedRelationshipDB(
            id=rel_uuid, type="CAUSES", source_concept_id=uuid.uuid4(), target_concept_id=uuid.uuid4(),
            created_at=datetime.now(timezone.utc), updated_at=datetime.now(timezone.utc)
        )
        mock_db_session.query(DirectedRelationshipDB).filter(DirectedRelationshipDB.id == rel_uuid).first.return_value = mock_db_rel

        result = await rel_repo.get_by_id(rel_id_str)

        assert result is not None
        assert result.id == rel_id_str
        assert result.type == "CAUSES"

    @pytest.mark.asyncio
    async def test_get_by_id_not_found_rel(self, rel_repo: SQLAlchemyRelationshipRepository, mock_db_session: MagicMock):
        rel_id_str = str(uuid.uuid4())
        rel_uuid = uuid.UUID(rel_id_str)
        mock_db_session.query(DirectedRelationshipDB).filter(DirectedRelationshipDB.id == rel_uuid).first.return_value = None

        result = await rel_repo.get_by_id(rel_id_str)
        assert result is None

    @pytest.mark.asyncio
    async def test_list_all_with_pagination_rel(self, rel_repo: SQLAlchemyRelationshipRepository, mock_db_session: MagicMock):
        mock_db_rels = [
            DirectedRelationshipDB(id=uuid.uuid4(), type="TYPE_A", source_concept_id=uuid.uuid4(), target_concept_id=uuid.uuid4(), created_at=datetime.now(timezone.utc), updated_at=datetime.now(timezone.utc)),
            DirectedRelationshipDB(id=uuid.uuid4(), type="TYPE_B", source_concept_id=uuid.uuid4(), target_concept_id=uuid.uuid4(), created_at=datetime.now(timezone.utc), updated_at=datetime.now(timezone.utc))
        ]
        mock_query = mock_db_session.query(DirectedRelationshipDB)
        mock_query.offset().limit().all.return_value = mock_db_rels

        result = await rel_repo.list_all(skip=2, limit=5)

        mock_query.offset.assert_called_with(2)
        mock_query.offset().limit.assert_called_with(5)
        mock_query.offset().limit().all.assert_called_once()

        assert len(result) == 2
        assert result[0].type == "TYPE_A"

    @pytest.mark.asyncio
    async def test_count_all_relationships(self, rel_repo: SQLAlchemyRelationshipRepository, mock_db_session: MagicMock):
        mock_db_session.query().scalar.return_value = 10

        count = await rel_repo.count_all()

        assert count == 10
        # Similar to concept count, detailed assertion of func.count is more involved
        # than needed for this level of unit test if the scalar return is correctly mocked.
