"""create_experiments_and_ttest_results_tables

Revision ID: stats_init_0001
Revises:
Create Date: 2024-07-30 15:00:00.000000 # Placeholder date

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'stats_init_0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group_a_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('group_b_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mlflow_run_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tracking_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_mlflow_run_id'), 'experiments', ['mlflow_run_id'], unique=False)

    op.create_table('ttest_results',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('experiment_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('statistic', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=False),
    sa.Column('degrees_freedom', sa.Float(), nullable=False),
    sa.Column('mean_group_a', sa.Float(), nullable=False),
    sa.Column('variance_group_a', sa.Float(), nullable=False),
    sa.Column('mean_group_b', sa.Float(), nullable=False),
    sa.Column('variance_group_b', sa.Float(), nullable=False),
    sa.Column('confidence_interval_95_lower', sa.Float(), nullable=False),
    sa.Column('confidence_interval_95_upper', sa.Float(), nullable=False),
    sa.Column('is_significant_05', sa.Boolean(), nullable=False),
    sa.Column('normality_p_value_group_a', sa.Float(), nullable=True),
    sa.Column('normality_p_value_group_b', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id') # Ensures one-to-one relationship
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ttest_results')
    op.drop_index(op.f('ix_experiments_mlflow_run_id'), table_name='experiments')
    op.drop_table('experiments')
    # ### end Alembic commands ###
```
